### ISSUE TITLE
Error when using Geo Range Search

### ISSUE THREAD

**Issue by jmaas-onoffice** [onOffice-Web-Org/oo-wp-plugin#428]
In an estate list, when I add the field "Geo Range Search > Geo Position", the frontend outputs the following error:

```
onOffice\WPlugin\Field\UnknownFieldException in /var/www/html/wp/wp-content/plugins/onoffice-for-wp-websites/plugin/Types/FieldsCollection.php:98
Stack trace:
#0 /var/www/html/wp/wp-content/plugins/onoffice-for-wp-websites/plugin/EstateList.php(483): onOffice\WPlugin\Types\FieldsCollection->getFieldByModuleAndName()
#1 /var/www/html/wp/wp-content/plugins/onoffice-for-wp-websites/plugin/EstateList.php(738): onOffice\WPlugin\EstateList->getFieldLabel()
#2 /var/www/html/wp/wp-content/plugins/onoffice-personalized/templates/estate/SearchForm.php(23): onOffice\WPlugin\EstateList->getVisibleFilterableFields()
#3 /var/www/html/wp/wp-content/plugins/onoffice-for-wp-websites/plugin/Template.php(118): include('...')
#4 /var/www/html/wp/wp-content/plugins/onoffice-for-wp-websites/plugin/Template.php(82): onOffice\WPlugin\Template::getIncludeContents()
#5 /var/www/html/wp/wp-content/plugins/onoffice-for-wp-websites/plugin/Controller/ContentFilter/ContentFilterShortCodeEstateList.php(137): onOffice\WPlugin\Template->render()
#6 /var/www/html/wp/wp-content/plugins/onoffice-for-wp-websites/plugin/Controller/ContentFilter/ContentFilterShortCodeEstate.php(94): onOffice\WPlugin\Controller\ContentFilter\ContentFilterShortCodeEstateList->render()
#7 /var/www/html/wp/wp-content/plugins/onoffice-for-wp-websites/plugin/Controller/ContentFilter/ContentFilterShortCodeEstate.php(69): onOffice\WPlugin\Controller\ContentFilter\ContentFilterShortCodeEstate->buildReplacementString()
#8 /var/www/html/wp/wp-content/plugins/onoffice-for-wp-websites/plugin/Controller/ContentFilter/ContentFilterShortCodeRegistrator.php(59): onOffice\WPlugin\Controller\ContentFilter\ContentFilterShortCodeEstate->replaceShortCodes()
#9 /var/www/html/wp/wp-includes/shortcodes.php(355): onOffice\WPlugin\Controller\ContentFilter\ContentFilterShortCodeRegistrator->onOffice\WPlugin\Controller\ContentFilter\{closure}()
#10 [internal function]: do_shortcode_tag()
#11 /var/www/html/wp/wp-includes/shortcodes.php(227): preg_replace_callback()
#12 /var/www/html/wp/wp-content/themes/beurretpartner/front-page.php(102): do_shortcode()
#13 /var/www/html/wp/wp-includes/template-loader.php(106): include('...')
#14 /var/www/html/wp/wp-blog-header.php(19): require_once('...')
#15 /var/www/html/wp/index.php(17): require('...')
#16 {main}
```

**Comment by dai-eastgate** [comment]
@jmaas-onoffice I fixed, you can watch video and give me feedback 

https://user-images.githubusercontent.com/106214469/215994954-7f8c4f8d-1e29-4edb-9320-a727bd63ed14.mp4

**Comment by jmaas-onoffice** [comment]
Looks good, thanks!
