### ISSUE TITLE
"multiParkingLot" generates critical error

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#654]
# Current state

If the "mulitParkingLot" field is saved without values such as "Vermarktungsart" and "Price" in onOffice enterprise it will generate a critical error on websites using the onOffice for WP-Websites plugin. The only fix for customers right now is to open the editing mask in onOffice enterprise and save again.

<details><summary>E.g. debug log 1</summary>
<p>

[10-Oct-2023 11:40:16 UTC] WordPress database error Table 'wp_rbm_prod.wp_rb_brokerredirection_items' doesn't exist for query SELECT * FROM wp_rb_brokerredirection_items WHERE match_url IN ('/detailansicht-immobilie/769', '/detailansicht-immobilie/769', 'regex') AND status='enabled' LIMIT 20000 made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WordPress_Module->init, Red_Item::get_for_url, Red_Item::get_for_matched_url
[10-Oct-2023 11:40:16 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:16 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:16 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:16 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:16 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:16 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:16 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:16 UTC] PHP Fatal error:  Uncaught TypeError: onOffice\WPlugin\Field\FieldParkingLot::formatPriceParking(): Argument #1 ($str) must be of type string, null given, called in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Field/FieldParkingLot.php on line 58 and defined in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Field/FieldParkingLot.php:71
Stack trace:
#0 /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Field/FieldParkingLot.php(58): onOffice\WPlugin\Field\FieldParkingLot->formatPriceParking()
#1 /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/EstateList.php(511): onOffice\WPlugin\Field\FieldParkingLot->renderParkingLot()
#2 /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataDetailViewCheckAccessControl.php(72): onOffice\WPlugin\EstateList->estateIterator()
#3 /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin.php(265): onOffice\WPlugin\DataView\DataDetailViewCheckAccessControl->checkRestrictAccess()
#4 /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/class-wp-hook.php(310): {closure}()
#5 /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#6 /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/plugin.php(565): WP_Hook->do_action()
#7 /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/class-wp.php(398): do_action_ref_array()
#8 /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/class-wp.php(779): WP->parse_request()
#9 /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/functions.php(1335): WP->main()
#10 /var/www/vhosts/rb-makler.de/httpdocs/wp-blog-header.php(16): wp()
#11 /var/www/vhosts/rb-makler.de/httpdocs/index.php(17): require('...')
#12 {main}
  thrown in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Field/FieldParkingLot.php on line 71
[10-Oct-2023 11:40:17 UTC] WordPress database error Table 'wp_rbm_prod.wp_rb_brokerredirection_items' doesn't exist for query SELECT * FROM wp_rb_brokerredirection_items WHERE match_url IN ('/robots.txt', '/robots.txt?1696938016415', 'regex') AND status='enabled' LIMIT 20000 made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WordPress_Module->init, Red_Item::get_for_url, Red_Item::get_for_matched_url
[10-Oct-2023 11:40:18 UTC] WordPress database error Table 'wp_rbm_prod.wp_rb_brokerredirection_items' doesn't exist for query SELECT * FROM wp_rb_brokerredirection_items WHERE match_url IN ('/detailansicht-immobilie/765', '/detailansicht-immobilie/765', 'regex') AND status='enabled' LIMIT 20000 made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WordPress_Module->init, Red_Item::get_for_url, Red_Item::get_for_matched_url
[10-Oct-2023 11:40:18 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:18 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:18 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:18 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:18 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:18 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:18 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:18 UTC] PHP Fatal error:  Uncaught TypeError: onOffice\WPlugin\Field\FieldParkingLot::formatPriceParking(): Argument #1 ($str) must be of type string, null given, called in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Field/FieldParkingLot.php on line 58 and defined in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Field/FieldParkingLot.php:71
Stack trace:
#0 /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Field/FieldParkingLot.php(58): onOffice\WPlugin\Field\FieldParkingLot->formatPriceParking()
#1 /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/EstateList.php(511): onOffice\WPlugin\Field\FieldParkingLot->renderParkingLot()
#2 /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataDetailViewCheckAccessControl.php(72): onOffice\WPlugin\EstateList->estateIterator()
#3 /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin.php(265): onOffice\WPlugin\DataView\DataDetailViewCheckAccessControl->checkRestrictAccess()
#4 /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/class-wp-hook.php(310): {closure}()
#5 /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#6 /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/plugin.php(565): WP_Hook->do_action()
#7 /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/class-wp.php(398): do_action_ref_array()
#8 /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/class-wp.php(779): WP->parse_request()
#9 /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/functions.php(1335): WP->main()
#10 /var/www/vhosts/rb-makler.de/httpdocs/wp-blog-header.php(16): wp()
#11 /var/www/vhosts/rb-makler.de/httpdocs/index.php(17): require('...')
#12 {main}
  thrown in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Field/FieldParkingLot.php on line 71
[10-Oct-2023 11:40:19 UTC] WordPress database error Table 'wp_rbm_prod.wp_rb_brokerredirection_items' doesn't exist for query SELECT * FROM wp_rb_brokerredirection_items WHERE match_url IN ('/robots.txt', '/robots.txt?1696938018223', 'regex') AND status='enabled' LIMIT 20000 made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WordPress_Module->init, Red_Item::get_for_url, Red_Item::get_for_matched_url
[10-Oct-2023 11:40:20 UTC] WordPress database error Table 'wp_rbm_prod.wp_rb_brokerredirection_items' doesn't exist for query SELECT * FROM wp_rb_brokerredirection_items WHERE match_url IN ('/detailansicht-immobilie/771', '/detailansicht-immobilie/771', 'regex') AND status='enabled' LIMIT 20000 made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WordPress_Module->init, Red_Item::get_for_url, Red_Item::get_for_matched_url
[10-Oct-2023 11:40:20 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:20 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:20 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:20 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:20 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:20 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:20 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:20 UTC] PHP Fatal error:  Uncaught TypeError: onOffice\WPlugin\Field\FieldParkingLot::formatPriceParking(): Argument #1 ($str) must be of type string, null given, called in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Field/FieldParkingLot.php on line 58 and defined in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Field/FieldParkingLot.php:71
Stack trace:
#0 /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Field/FieldParkingLot.php(58): onOffice\WPlugin\Field\FieldParkingLot->formatPriceParking()
#1 /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/EstateList.php(511): onOffice\WPlugin\Field\FieldParkingLot->renderParkingLot()
#2 /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataDetailViewCheckAccessControl.php(72): onOffice\WPlugin\EstateList->estateIterator()
#3 /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin.php(265): onOffice\WPlugin\DataView\DataDetailViewCheckAccessControl->checkRestrictAccess()
#4 /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/class-wp-hook.php(310): {closure}()
#5 /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#6 /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/plugin.php(565): WP_Hook->do_action()
#7 /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/class-wp.php(398): do_action_ref_array()
#8 /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/class-wp.php(779): WP->parse_request()
#9 /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/functions.php(1335): WP->main()
#10 /var/www/vhosts/rb-makler.de/httpdocs/wp-blog-header.php(16): wp()
#11 /var/www/vhosts/rb-makler.de/httpdocs/index.php(17): require('...')
#12 {main}
  thrown in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Field/FieldParkingLot.php on line 71
[10-Oct-2023 11:40:21 UTC] WordPress database error Table 'wp_rbm_prod.wp_rb_brokerredirection_items' doesn't exist for query SELECT * FROM wp_rb_brokerredirection_items WHERE match_url IN ('/robots.txt', '/robots.txt?1696938020456', 'regex') AND status='enabled' LIMIT 20000 made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WordPress_Module->init, Red_Item::get_for_url, Red_Item::get_for_matched_url
[10-Oct-2023 11:40:22 UTC] WordPress database error Table 'wp_rbm_prod.wp_rb_brokerredirection_items' doesn't exist for query SELECT * FROM wp_rb_brokerredirection_items WHERE match_url IN ('/xmlrpc.php', '/xmlrpc.php', 'regex') AND status='enabled' LIMIT 20000 made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WordPress_Module->init, Red_Item::get_for_url, Red_Item::get_for_matched_url
[10-Oct-2023 11:40:22 UTC] WordPress database error Table 'wp_rbm_prod.wp_rb_brokerredirection_items' doesn't exist for query SELECT * FROM wp_rb_brokerredirection_items WHERE match_url IN ('/detailansicht-immobilie/1287', '/detailansicht-immobilie/1287', 'regex') AND status='enabled' LIMIT 20000 made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WordPress_Module->init, Red_Item::get_for_url, Red_Item::get_for_matched_url
[10-Oct-2023 11:40:22 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:22 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:22 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:22 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:22 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:22 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:22 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:22 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:22 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:22 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:22 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:22 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:22 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:22 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 126
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 185
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 235
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 237
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 253
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 327
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 335
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 345
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 347
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 364
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 390
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 407
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 415
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 437
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 439
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 457
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 552
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 562
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 670
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 792
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 794
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 812
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 845
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 856
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 1617
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "pin" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 1665
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "status" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/form/immobilien-anfrage-kauf.php on line 46
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "status" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/form/immobilien-anfrage-kauf.php on line 50
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined array key "status" in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/form/immobilien-anfrage-kauf.php on line 52
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined variable $urldatenschutz in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/form/immobilien-anfrage-kauf.php on line 117
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined variable $company in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/form/immobilien-anfrage-kauf.php on line 117
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined variable $company in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/form/immobilien-anfrage-kauf.php on line 128
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Undefined variable $company in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-personalized/templates/estate/default_detail.php on line 1791
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:23 UTC] PHP Warning:  Array to string conversion in /var/www/vhosts/rb-makler.de/httpdocs/wp-includes/formatting.php on line 1104
[10-Oct-2023 11:40:23 UTC] WordPress database error Table 'wp_rbm_prod.wp_rb_brokerredirection_items' doesn't exist for query SELECT * FROM wp_rb_brokerredirection_items WHERE match_url IN ('/wp-content/uploads/2023/07/reviews-block.png.webp', '/wp-content/uploads/2023/07/reviews-block.png.webp', 'regex') AND status='enabled' LIMIT 20000 made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WordPress_Module->init, Red_Item::get_for_url, Red_Item::get_for_matched_url
[10-Oct-2023 11:40:23 UTC] WordPress database error Table 'wp_rbm_prod.wp_rb_brokerredirection_404' doesn't exist for query SHOW FULL COLUMNS FROM `wp_rb_brokerredirection_404` made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WordPress_Module->template_redirect, Red_404_Log::create
[10-Oct-2023 11:40:24 UTC] WordPress database error Table 'wp_rbm_prod.wp_rb_brokerredirection_items' doesn't exist for query SELECT * FROM wp_rb_brokerredirection_items WHERE match_url IN ('/robots.txt', '/robots.txt?1696938022969', 'regex') AND status='enabled' LIMIT 20000 made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WordPress_Module->init, Red_Item::get_for_url, Red_Item::get_for_matched_url

</p>
</details> 

# Desired state

"Argument #1 ($str) must be of type string, null given"
Even if nothing or "wrong" data is transmitted from the multiParkingLot field, the onOffice for WP-Websites plugin should not have a critical error. This must be handled beforehand and properly resolved.

**Comment by dai-eastgate** [comment]
> Argument #1 ($str) must be of type string, null given, called in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Field/FieldParkingLot.php on line 58 and defined in /var/www/vhosts/rb-makler.de/httpdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Field/FieldParkingLot.php:71

@fredericalpers Currently, I cannot reproduce this bug. Please record a video of the error, so we can better understand and fix this bug. Thanks!

**Comment by fredericalpers** [comment]
@dai-eastgate I will investigate further and see what I can find, thank you

**Comment by fredericalpers** [comment]
Bug can not be reproduced anymore. The bug in onOffice enterprise will be fixed separately.
